import type { Project, StackGroup } from "@/types";

export const site = {
  name: "Alexandru Ghiura",
  handle: "ghalex",
  domain: "ghalex.dev",
  tagline: "I love building products from zero.",
  description: "Founder, engineer, builder of things.",
  email: "ghalex@gmail.com",
  location: "Timisoara, Romania",
  locationShort: "Timisoara, RO",
  timeZone: "Europe/Bucharest",
  timeZoneLabel: "Timisoara (GMT+3)",
  shippingSince: "2006",
  x: "https://x.com/ghalex",
  github: "https://github.com/ghalex",
  linkedin: "https://linkedin.com/in/ghalex",
  logzai: "https://logzai.com",
  zenve3d: "https://zenve3d.com",
};

export const about = [
  "I'm a builder at heart. After 20 years in software I keep coming back to the same thing: taking an idea from zero to a working product with my own hands — the storage engine, the UI, the go-to-market, all of it.",
  "Right now that means [LogzAI](https://logzai.com), an AI-native log observability platform I built solo on a hand-built Delta Lake storage engine (one of 3 winners at the inVest accelerator Demo Day), and [Zenve3d](https://zenve3d.com), my newest venture. Before these I co-founded Zapant, a trading platform that executed 300K+ live transactions, bootstrapped from AntSignals — a trading-journal SaaS I grew to ~€2K/month with zero ad spend.",
  "I like hard technical problems (I once wrote an OS from scratch), small teams, and products that make money without permission.",
];

export const projects: Project[] = [
  {
    name: "Zenve3D",
    url: "https://zenve3d.com",
    role: "Founder · Professional parametric CAD for makers",
    meta: "beta",
    active: true,
    logoSrc: "/logos/zenve3d.png",
    bullets: [
      "**Full parametric CAD** — editable sketches, constraints, dimensions, features, and a complete modeling history: change an early dimension and the rest of the model updates with it.",
      "Every field takes **expressions** — a parameter's name works anywhere a number does.",
      "One modern **C++ geometry engine**, native on macOS and iPad — touch and Pencil on the tablet, full desktop workflows on the Mac.",
      "Built-in **MCP server** — AI assistants plug straight into the modeler: sketch, model, and inspect parts through natural language.",
      "Professional CAD workflows **without enterprise complexity or enterprise pricing** — built for makers: 3D-printed parts, CNC components, robotics, enclosures, prototypes.",
    ],
    tags: ["C++", "Swift", "Geometry kernel", "MCP", "macOS", "iPad"],
  },
  {
    name: "LogzAI",
    url: "https://logzai.com",
    role: "Founder · AI-native log observability platform",
    meta: "active",
    active: true,
    logoSrc: "/logos/logzai.png",
    bullets: [
      "**AI-native log analysis** — chat with your logs, get any log explained, and let automatic pattern and anomaly detection surface problems before you go looking.",
      "**Purpose-built log agent** — custom tool suite and prompt architecture that plans multi-step investigations across millions of logs and answers with evidence.",
      "Custom storage engine on the **Delta Lake open format**, over S3 or local disk — **6M+ logs** for a single organization, full-dataset SQL queries in seconds.",
      "**Full SQL** over everything through DuckDB — query builder with attribute filters, saved and shared queries, and smart alerts when something goes wrong.",
      "Open format end-to-end: no bespoke index, **no lock-in** — any tool that reads Delta Lake can read your logs.",
    ],
    tags: [
      "TypeScript",
      "Node.js",
      "Python",
      "DuckDB",
      "Delta Lake",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    name: "Zapant",
    url: "https://zapant.com",
    role: "Co-Founder & CEO · Automated trading platform",
    meta: "300K+ tx",
    active: false,
    logoSrc: "/logos/zapant.png",
    bullets: [
      "**Automated trading bots** for stocks and crypto — pick a public bot with strict risk-management protocols, connect your broker, and go live in minutes.",
      "[**Zplang**](https://zaplang.com), an open-source Clojure-inspired trading language with built-in assets and indicators — a strategy is a few lines of code, backtested and executed from the terminal with [**ZapCLI**](https://zapcli.com).",
      "**Custom strategies** — write your own bots in JavaScript or Zplang and run them live on the platform.",
      "**300,000+ live transactions** executed against real brokers, with real money on the line.",
    ],
    tags: ["TypeScript", "React", "Node.js", "Zplang"],
  },
  {
    name: "AntSignals",
    url: "https://antsignals.com",
    role: "Solo founder · Trading-journal SaaS",
    meta: "€2K MRR",
    active: true,
    logoSrc: "/logos/antsignals.png",
    bullets: [
      "**A trading journal that finds your edge** — import trades straight from your broker and let the reports show which setups make money and which quietly bleed it.",
      "**Data-driven feedback** on everything: peak-performance hours, position sizing, pattern and mistake detection — across stocks, indices, forex, options, and crypto.",
      "**AI insights, a trade simulator**, and multiple portfolios with customizable reports and rich data visualization.",
      "Independently reviewed — [Bullish Bears](https://bullishbears.com/antsignals-review/) calls its **data-driven feedback** the platform's biggest strength.",
    ],
    tags: ["TypeScript", "Vue", "Node.js"],
  },
  {
    name: "vue3-charts",
    url: "https://github.com/ghalex/vue3-charts",
    role: "SVG charting library for Vue 3",
    meta: "150+ stars",
    active: false,
    logoSrc: "/logos/vue3charts.png",
    bullets: [
      "**#1 search result for “vue3 charts”** — SVG charting for Vue 3, intuitive and extensible.",
      "**Charts are templates** — Grid, Bar, Line, and Area compose as declarative layers.",
      "Docs and live examples at [vue3charts.org](https://vue3charts.org).",
      "Built on top of **D3** — D3's math, Vue's reactivity.",
    ],
    tags: ["Vue 3", "SVG", "TypeScript"],
  },
  {
    name: "PhiOS",
    url: "https://github.com/ghalex/phios",
    role: "Operating system from scratch",
    meta: "hobby",
    active: false,
    bullets: [
      "**Boots on bare metal** — assembly bootloader into a C++ kernel, shipped as a bootable x86 image.",
      "**C++ with no OS underneath** — hand-rolled runtime support, VGA text driver, port-I/O layer, custom linker script.",
      "Runs in **QEMU** straight from the repo — x64 and ARM ports sketched in the tree.",
    ],
    tags: ["Assembly", "C++", "x86"],
  },
];

export const stack: StackGroup[] = [
  {
    num: "01",
    name: "Languages",
    items: ["TypeScript", "JavaScript", "Python", "C++", "C", "C#"],
  },
  {
    num: "02",
    name: "AI Engineering",
    items: [
      "AI System Design",
      "Multi-Agent Systems",
      "RAG Pipelines",
      "MCP & Tools",
      "Agentic Workflows",
      "Custom Architectures",
      "Claude & LLM APIs"
    ],
  },
  {
    num: "03",
    name: "Data",
    items: ["Delta Lake", "Parquet", "DuckDB", "Storage engines", "S3"],
  },
  {
    num: "04",
    name: "Backend",
    items: [
      "Node.js",
      "Moleculer microservices",
      "FastAPI",
      "Real-time & event-driven",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "NATS",
      "RabbitMQ",
      "Kafka",
      "Docker",
      "Kubernetes",
    ],
  },
  {
    num: "05",
    name: "Frontend",
    items: [
      "HTML & CSS",
      "React",
      "React Native",
      "Vue",
      "Mobile apps",
      "SVG / charts",
      "Every framework since jQuery",
    ],
  },
  { num: "06", name: "Cloud", items: ["AWS", "Azure", "GCP", "Linode"] },
  {
    num: "07",
    name: "Leadership",
    items: [
      "Org building from zero",
      "EM → Senior EM",
      "Hiring at scale",
      "M&A team transition",
      "Pre-sales & RFPs",
      "EM mentoring",
    ],
  },
];

